### ISSUE TITLE
cant create output

### ISSUE THREAD

**Issue by oriziv** [jxnblk/figma-theme#1]
Awesome work!

seems that its not aligned to latest schema
its failing when i run it, here is the stack trace

TypeError: Cannot read property 'value' of undefined
    at textStyles.map.map.style (index.js:103:17)
    at Array.map (<anonymous>)
    at module.exports (index.js:97:6)
    at figma.file.then.res (cli.js:91:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
TypeError: Cannot read property 'status' of undefined
    at figma.file.then.catch.err (cli.js:107:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by jxnblk** [comment]
Thanks! I think I see the bug on my end. I’m guessing the file you tried has a text style that isn’t applied in the document. This library has to do some extra work because of the way styles are currently returned in the Figma API. See this thread: https://spectrum.chat/figma?thread=6bbf7bb4-b78d-47c9-9802-a2c50c10d4eb

**Comment by oriziv** [comment]
OK Thanks

**Comment by oriziv** [comment]
Is it possible to have that option via configuration at least? 
Thanks!
